### ISSUE TITLE
Connectiong both nodes at the same time

### ISSUE THREAD

**Issue by raulsimcic** [estbeetoo/node-red-contrib-knx#10]
Hi,

I'm testing the node on my project. When I pun only the "out node" on the flow it connects and communicates with the KNX bus without any problem. If I put only the "in node" it connects without problem but I'm not reading any data from the bus, Ok, the testing bus has only the power supply, gateway and switch actuator but no signals from them. Till now good as it can be.

But, when I set both nodes on the flow "in" and "out" (as is described) they don't connect to the bus.

The configuration is set for both as described: ip address 192.168.1.19, port 3671

What I'm doing wrong?? 

I'm using iKNiX gateway ver 2.

**Comment by aborovsky** [comment]
Hi, @raulsimcic!

Please, provide your flow's json.
