### ISSUE TITLE
Unable to write group address

### ISSUE THREAD

**Issue by fluppie** [estbeetoo/node-red-contrib-knx#11]
Inject string: 
{"dstgad":"0/1/0","dpt":"1","value":0}

8-11-2016 19:55:00Nieuwe KNX OUTmsg : string [75]error calling groupAddrSend: TypeError: Object � has no method 'writeIntLE'
8-11-2016 19:55:00Nieuwe KNX OUTmsg : string [69]groupAddrSend error: [TypeError: Object � has no method 'writeIntLE']

Node-RED flow:
[{"id":"61c0d192.cdc99","type":"knx-out","z":"b5ff6476.19e4b8","name":"Nieuwe KNX OUT","controller":"498caeb8.491b6","x":385,"y":85,"wires":[]},{"id":"e5cc3fd1.b1752","type":"inject","z":"b5ff6476.19e4b8","name":"write 0/1/0","topic":"write","payload":"{\"dstgad\":\"0/1/0\",\"dpt\":\"1\",\"value\":0}","payloadType":"json","repeat":"","crontab":"","once":false,"x":133,"y":85,"wires":[["61c0d192.cdc99"]]},{"id":"498caeb8.491b6","type":"knx-controller","z":"","name":"KNX IP Interface","host":"192.168.1.5","port":"3671","mode":"tunnel/unicast"}]

Any idea what I do wrong?

node v0.10.29
npm v1.4.21
Node-RED v0.15.2

**Comment by aborovsky** [comment]
You definitely should update node.js to v4._._ or above.

Please, give a feedback if it will not help.
вт, 8 нояб. 2016 г. в 22:03, fluppie notifications@github.com:

**Comment by fluppie** [comment]
I did the update via the NVM script. Did an install of 4.6.2, a reboot of de Raspberry Pi and I'm getting the same errors as above.

node -v
v4.6.2
npm -v
2.15.11

9-11-2016 09:10:37Nieuwe KNX OUTmsg : string [75]error calling groupAddrSend: TypeError: Object x has no method 'writeIntLE'
9-11-2016 09:10:37Nieuwe KNX OUTmsg : string [69]groupAddrSend error: [TypeError: Object x has no method 'writeIntLE']

**Comment by aborovsky** [comment]
Are you sure, running node-red using exactly new one node.js?
Please, check the very beginning on node-red's startup output.
It write about environment and nodejs's version.

**Comment by ekarak** [comment]
Try ekarak/node-red-contrib-knxjs ;)

Στις 9 Νοε 2016 15:06, ο χρήστης "Alexander Borovsky" <
notifications@github.com> έγραψε:

**Comment by aborovsky** [comment]
Hey-hey, advertising without acceptance? :)

ср, 9 нояб. 2016 г. в 16:15, Elias Karakoulakis notifications@github.com:

**Comment by fluppie** [comment]
Yes I'm sure :)

# Welcome to Node-RED

9 Nov 15:47:38 - [info] Node-RED version: v0.15.2
9 Nov 15:47:38 - [info] Node.js  version: v4.6.2
9 Nov 15:47:38 - [info] Linux 4.1.19-v7+ arm LE
9 Nov 15:47:39 - [info] Loading palette nodes
9 Nov 15:47:44 - [warn] ------------------------------------------------------
9 Nov 15:47:44 - [warn] [serialport] Error: Module did not self-register.
9 Nov 15:47:44 - [warn] ------------------------------------------------------
9 Nov 15:47:44 - [info] Settings file  : /home/pi/.node-red/settings.js
9 Nov 15:47:44 - [info] User directory : /home/pi/.node-red
9 Nov 15:47:44 - [info] Flows file     : /home/pi/.node-red/flows_emonpi.json

**Comment by aborovsky** [comment]
I've cheked it on my own Raspberry Pi 3.

```
Welcome to Node-RED
===================

14 Nov 14:36:14 - [info] Node-RED version: v0.15.2
14 Nov 14:36:14 - [info] Node.js  version: v4.6.2
14 Nov 14:36:14 - [info] Linux 4.4.23-v7+ arm LE
14 Nov 14:36:15 - [info] Loading palette nodes
14 Nov 14:36:23 - [info] UI started at /ui
14 Nov 14:36:23 - [info] Settings file  : /root/.node-red/settings.js
14 Nov 14:36:23 - [info] User directory : /root/.node-red
14 Nov 14:36:23 - [info] Flows file     : /root/.node-red/flows_raspberrypi.json
14 Nov 14:36:23 - [info] Server now running at http://127.0.0.1:1880/
14 Nov 14:36:23 - [info] Starting flows
14 Nov 14:36:23 - [info] Started flows
```

Your flow:

```
[{"id":"35954602.6c11aa","type":"tab","label":"Flow 1"},{"id":"c8bb7e1a.e183e","type":"knx-controller","z":"","name":"KNX IP Interface","host":"192.168.2.222","port":"3671","mode":"tunnel/unicast"},{"id":"47f2ef37.4962a","type":"knx-out","z":"35954602.6c11aa","name":"Nieuwe KNX OUT","controller":"c8bb7e1a.e183e","x":388.2000274658203,"y":82.19999694824219,"wires":[]},{"id":"f1ca1961.9b5e78","type":"inject","z":"35954602.6c11aa","name":"write 0/1/0","topic":"write","payload":"{\"dstgad\":\"0/1/0\",\"dpt\":\"1\",\"value\":0}","payloadType":"json","repeat":"","crontab":"","once":false,"x":136.2000274658203,"y":82.19999694824219,"wires":[["47f2ef37.4962a"]]}]
```

And sucessfull result:

![image](https://cloud.githubusercontent.com/assets/1669420/20263698/fe8d4e2e-aa78-11e6-9437-7305cac8b896.png)

Success log output:

```
14 Nov 14:44:48 - [info] [knx-out:Nieuwe KNX OUT] knxout.onInput, msg[{ _msgid: '990ed5d4.66f128',
  topic: 'write',
  payload: { dstgad: '0/1/0', dpt: '1', value: 0 } }]
14 Nov 14:44:48 - [info] [knx-out:Nieuwe KNX OUT] groupAddrSend action[write] dstgad:0/1/0, value:0, dpt:1
14 Nov 14:44:48 - [info] [knx-controller:KNX IP Interface] connecting to knxjs server at 192.168.2.222:3671 in mode[tunnel/u                      nicast]
14 Nov 14:44:48 - [info] [knx-controller:KNX IP Interface] Knx: successfully connected to 192.168.2.222:3671 in mode[tunnel/                      unicast]
14 Nov 14:44:48 - [info] [knx-out:Nieuwe KNX OUT] sendAPDU: false
```

Packages versions:
- node-red-contrib-knx-0.7.6
- knx.js-0.6.11 (node-red-contrib-knx depends on knx.js)

Do you experiencing current trouble right now?

**Comment by fluppie** [comment]
Hi Alexander,

I'm going to retry this tonight. Maybe it's because of my MDT KNX IP
interface? But it has worked in the past (on a older version).

Regards,

Philippe

**Comment by aborovsky** [comment]
It's connected with software, i'm almost 100% sure :)

Do you know JavaScript enough? To inject small debug code, to fogure out what's going on...

**Comment by fluppie** [comment]
Injecting a debug code will work. Writing it myself, no :).

Btw, I have the same package.

pi@emonpi(rw):~$ sudo npm install node-red-contrib-knx
node-red-contrib-knx@0.7.6 node_modules/node-red-contrib-knx
└── knx.js@0.6.11 (promise@7.1.1)
pi@emonpi(rw):~$ node -v
v4.6.2

**Comment by aborovsky** [comment]
1. Choose your node-red's installation dir:
   - In case of global install: `~/.npm`.
   - In case of local install: `/home/pi/example_dir/node-red`.  
     Let's call it `$NODERED_HOME`.
2. Open for edit:
   `nano $NODERED_HOME/node_modules/node-red-contrib-knx/node_modules/knx.js/src/KnxConnection.js`
3. Find line 86:
   `buf.writeIntLE(data ? 1 : 0);`
4. Insert strictly BETWEEN line 85 and line 86:
   
   ```
   console.log('---------- Going to call Buffer.writeIntLE');
   console.log('---------- NodeJS');
   console.log(require('util').inspect(process.versions));
   console.log('---------- Buffer.prototype');
   console.log(require('util').inspect(Buffer.prototype));
   ```
5. Then run you flow (press inject) and get output:

```
14 Nov 17:27:50 - [info] [knx-out:Nieuwe KNX OUT] knxout.onInput, msg[{ _msgid: '85ac4f8a.7a53b',
  topic: 'write',
  payload: '{"dstgad":"0/1/0","dpt":"1","value":0}' }]
14 Nov 17:27:50 - [info] [knx-out:Nieuwe KNX OUT] groupAddrSend action[write] dstgad:0/1/0, value:0, dpt:1
14 Nov 17:27:50 - [info] [knx-controller:KNX IP Interface] connecting to knxjs server at 192.168.2.222:3671 in mode[tunnel/unicast]
14 Nov 17:27:50 - [info] [knx-controller:KNX IP Interface] Knx: successfully connected to 192.168.2.222:3671 in mode[tunnel/unicast]
14 Nov 17:27:50 - [info] [knx-out:Nieuwe KNX OUT] sendAPDU: false
---------- Going to call Buffer.writeIntLE
---------- NodeJS
{ http_parser: '2.7.0',
  node: '4.6.2',
  v8: '4.5.103.42',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2j' }
---------- Buffer.prototype
Buffer {
  asciiSlice: [Function: asciiSlice],
  base64Slice: [Function: base64Slice],
  binarySlice: [Function: binarySlice],
  hexSlice: [Function: hexSlice],
  ucs2Slice: [Function: ucs2Slice],
  utf8Slice: [Function: utf8Slice],
  asciiWrite: [Function: asciiWrite],
  base64Write: [Function: base64Write],
  binaryWrite: [Function: binaryWrite],
  hexWrite: [Function: hexWrite],
  ucs2Write: [Function: ucs2Write],
  utf8Write: [Function: utf8Write],
  copy: [Function: copy],
  parent: [Getter],
  offset: [Getter],
  toString: [Function],
  equals: [Function: equals],
  inspect: [Function: inspect],
  compare: [Function: compare],
  indexOf: [Function: indexOf],
  fill: [Function: fill],
  get: [Function: deprecated],
  set: [Function: deprecated],
  write: [Function],
  toJSON: [Function],
  slice: [Function: slice],
  readUIntLE: [Function],
  readUIntBE: [Function],
  readUInt8: [Function],
  readUInt16LE: [Function],
  readUInt16BE: [Function],
  readUInt32LE: [Function],
  readUInt32BE: [Function],
  readIntLE: [Function],
  readIntBE: [Function],
  readInt8: [Function],
  readInt16LE: [Function],
  readInt16BE: [Function],
  readInt32LE: [Function],
  readInt32BE: [Function],
  readFloatLE: [Function: readFloatLE],
  readFloatBE: [Function: readFloatBE],
  readDoubleLE: [Function: readDoubleLE],
  readDoubleBE: [Function: readDoubleBE],
  writeUIntLE: [Function],
  writeUIntBE: [Function],
  writeUInt8: [Function],
  writeUInt16LE: [Function],
  writeUInt16BE: [Function],
  writeUInt32LE: [Function],
  writeUInt32BE: [Function],
  writeIntLE: [Function],
  writeIntBE: [Function],
  writeInt8: [Function],
  writeInt16LE: [Function],
  writeInt16BE: [Function],
  writeInt32LE: [Function],
  writeInt32BE: [Function],
  writeFloatLE: [Function: writeFloatLE],
  writeFloatBE: [Function: writeFloatBE],
  writeDoubleLE: [Function: writeDoubleLE],
  writeDoubleBE: [Function: writeDoubleBE] }
```

**Comment by fluppie** [comment]
Ok, something weird. When Node-Red is started as a service:

_pi@emonpi(rw):~$ sudo service nodered status● nodered.service - Node-RED
graphical event wiring tool.   Loaded: loaded
(/lib/systemd/system/nodered.service; enabled)   Active: active (running)
since Mon 2016-11-14 15:46:45 UTC; 6s ago     Docs:
http://nodered.org/docs/hardware/raspberrypi.html
http://nodered.org/docs/hardware/raspberrypi.html Main PID: 17787
(node)   CGroup: /system.slice/nodered.service           └─17787 node
--max-old-space-size=128 /usr/lib/node_modules/node-red/bin/../red.jsNov 14
15:46:47 emonpi Node-RED[17787]: Welcome to Node-REDNov 14 15:46:47 emonpi
Node-RED[17787]: ===================Nov 14 15:46:47 emonpi Node-RED[17787]:
14 Nov 15:46:47 - [info] Node-RED version: v0.15.2Nov 14 15:46:47 emonpi
Node-RED[17787]: 14 Nov 15:46:47 - [info] Node.js  version: v0.10.29Nov 14
15:46:47 emonpi Node-RED[17787]: 14 Nov 15:46:47 - [info] Linux 4.1.19-v7+
arm LENov 14 15:46:47 emonpi Node-RED[17787]: 14 Nov 15:46:47 - [info]
Palette editor disabled : npm command not foundNov 14 15:46:47 emonpi
Node-RED[17787]: 14 Nov 15:46:47 - [info] Loading palette nodesNov 14
15:46:48 emonpi sudo[17841]: pi : TTY=unknown ; PWD=/home/pi ; USER=root ;
COMMAND=/usr/bin/python -u /usr/lib/node_mod...py infoNov 14 15:46:48
emonpi sudo[17841]: pam_unix(sudo:session): session opened for user root by
(uid=0)Nov 14 15:46:48 emonpi sudo[17841]: pam_unix(sudo:session): session
closed for user rootHint: Some lines were ellipsized, use -l to show in
full._
When typing node-red in a ssh session:

*pi@emonpi(rw):~$ node-redWelcome to Node-RED===================14 Nov
15:48:28 - [info] Node-RED version: v0.15.214 Nov 15:48:28 - [info]
Node.js  version: v4.6.214 Nov 15:48:28 - [info] Linux 4.1.19-v7+ arm LE14
Nov 15:48:29 - [info] Loading palette nodes14 Nov 15:48:34 - [warn]
------------------------------------------------------14 Nov 15:48:34 -
[warn] [serialport] Error: Module did not self-register.14 Nov 15:48:34 -
[warn] ------------------------------------------------------14 Nov
15:48:34 - [info] Settings file  : /home/pi/.node-red/settings.js14 Nov
15:48:34 - [info] User directory : /home/pi/.node-red14 Nov 15:48:34 -
[info] Flows file     : /home/pi/.node-red/flows_emonpi.json14 Nov 15:48:34
- [info] Server now running at http://127.0.0.1:1880/
  http://127.0.0.1:1880/14 Nov 15:48:34 - [info] Starting flows14 Nov
  15:48:34 - [info] [knx-controller:KNX IP Interface] connecting to knxjs
  server at 192.168.1.5:3671 http://192.168.1.5:3671 in
  mode[tunnel/unicast]14 Nov 15:48:34 - [info] Started flows14 Nov 15:48:34 -
  [info] [knx-controller:KNX IP Interface] Knx: successfully connected to
  192.168.1.5:3671 http://192.168.1.5:3671 in mode[tunnel/unicast]14 Nov
  15:48:34 - [info] [mqtt-broker:8a9d92d6.75627] Connected to broker:
  mqtt://localhost:1883*
  When booting with 4.6.2 it works! So weird the service is booting via
  node.js 0.10.29 ...

**Comment by aborovsky** [comment]
A-ha. I knew - the reason is nodejs's version.
Try to check nodejs's binary:
1. If in some common dir (/bin, /usr/bin, /usr/local/bin) located old 'node' executable, then place here a symbolic link to new one.
2. And if not - check nodered service script, there are hard coded path to 'node' executable.
