### ISSUE TITLE
Can't make a DPT 5 or 5.001 work

### ISSUE THREAD

**Issue by fluppie** [estbeetoo/node-red-contrib-knx#12]
Node-Red flow:

`[{"id":"42d0b1e5.a4a3c","type":"inject","z":"f1b75694.9fa55","name":"2/1/1 dim value 10%","topic":"write","payload":"{\"dstgad\":\"2/1/1\",\"dpt\":\"5\",\"value\":10}","payloadType":"str","repeat":"","crontab":"","once":false,"x":502,"y":220.79998779296875,"wires":[["a5e67070.b931e8","290ccdf7.86a14a"]]},{"id":"a5e67070.b931e8","type":"knx-out","z":"f1b75694.9fa55","name":"KNX OUT","controller":"3a1c430d.b6143c","x":842,"y":74,"wires":[]},{"id":"3a1c430d.b6143c","type":"knx-controller","z":"","name":"KNX Interface","host":"192.168.1.5","port":"3671","mode":"tunnel/unicast"}]`

```
pi@emonpi(rw):~$ node -v
v6.10.0
pi@emonpi(rw):~$ npm -v
node3.10.10
pi@emonpi(rw):~$ node-red -v
26 Feb 20:39:01 - [info]

Welcome to Node-RED
===================

26 Feb 20:39:01 - [info] Node-RED version: v0.16.2
26 Feb 20:39:01 - [info] Node.js  version: v6.10.0
26 Feb 20:39:01 - [info] Linux 4.4.38-v7+ arm LE
26 Feb 20:39:02 - [info] Loading palette nodes
```

When I inject this node I get an error:
```

26-2-2017 21:39:36node: KNX OUTmsg : error
"ReferenceError: data is not defined"
26-2-2017 21:39:36node: 290ccdf7.86a14awrite : msg : Object
object
_msgid: "8fb84222.ae273"
topic: "write"
payload: "{"dstgad":"2/1/1","dpt":"5","value":10}"
```

When I use a DPT1 all is working fine, but DPT5 or DPT 5.001 isn't working.

**Comment by ykornilov** [comment]
Thank you for the error found. It should now work.

**Comment by fluppie** [comment]
Hi, sadly the fix gives the same error for me:

`27-2-2017 13:04:39node: KNX OUTmsg : error
"ReferenceError: data is not defined"
27-2-2017 13:04:39node: 290ccdf7.86a14awrite : msg : Object
object
_msgid: "8fb8401a.942ca"
topic: "write"
payload: "{"dstgad":"2/1/1","dpt":"5","value":10}"`

pi@emonpi(rw):oem_node-red$ sudo npm install node-red-contrib-knx
oem_node-red@1.0.0 /home/pi/oem_node-red
└── node-red-contrib-knx@0.8.1

**Comment by ykornilov** [comment]
Strange... I removed the node and re-installed it, imported your flow and
everything worked...
Please, open file 'knx,js'. In row 201 must be

'if (value <= 255) {'

instead of

'if (data <= 255) {'

2017-02-27 15:05 GMT+03:00 fluppie <notifications@github.com>:

**Comment by fluppie** [comment]
Weird, I had 3 installs of the knx node... I removed all and reinstalled one and all is working fine now :). Thanks!
