### ISSUE TITLE
Example  "dpt":"DPT1" in function incorrect - Gira1310

### ISSUE THREAD

**Issue by industrialinternet** [estbeetoo/node-red-contrib-knx#15]
Guys thanks for great work

Testing with old Gira 1030 - (Siemens clone) works well so far.
Have a BAOS771 too so will test later with that.
And if I can blag one,  will try it with latest Gira IP interface

One small issue function node example shows   "dpt":"DPT1", should be an integer  "dpt":1,
``` javasctip
var knxmsg = {  
   "topic":"write",
   "payload":{  
      "srcphy":"1.1.100",
      "dstgad":"15/1/0",
      "dpt":1,
      "value":1
   }
}
return knxmsg;
```

**Comment by ykornilov** [comment]
Thank you very much for your comment! Description fixed.
