### ISSUE TITLE
Can't send and recieve simultaneously

### ISSUE THREAD

**Issue by yanovik** [estbeetoo/node-red-contrib-knx#16]
Hello

When I add my KNX Both IN and OUT nodes only KNX IN node works, it passes all data, all bus commands are displayed. But I cant send commands to KNX OUT node, when i try i get
`27 Sep 07:07:56 - [info] [knx-out:Out] groupAddrSend action[write] dstgad:0/2/3, value:1, dpt:1
27 Sep 07:07:56 - [info] [knx-controller:BAOS777] already connected to knxjs server at 192.168.1.60:3671 in mode[tunnel/unicast]`

When I delete KNX IN node, KNX OUT node works fine

`27 Sep 07:20:17 - [info] Node-RED version: v0.17.5
27 Sep 07:20:17 - [info] Node.js  version: v6.11.3
27 Sep 07:20:17 - [info] Linux 4.9.41-v7+ arm LE`

I suppose i'm missing something?
ps flow export 
`[{"id":"14e27b21.883a85","type":"tab","label":"KNX","disabled":false,"info":""},{"id":"a9221435.2fe868","type":"knx-out","z":"14e27b21.883a85","name":"Out","controller":"40bc1d5d.22bf14","x":290,"y":100,"wires":[]},{"id":"9434c14b.2e807","type":"inject","z":"14e27b21.883a85","name":"","topic":"write","payload":"{\"srcphy\":\"1.1.3\",\"dstgad\":\"0/2/5\",\"dpt\":\"1\",\"value\":\"0\",\"type\":\"event\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":100,"wires":[["a9221435.2fe868","88718a66.6c0a28"]]},{"id":"6d5c1c5e.f5f334","type":"debug","z":"14e27b21.883a85","name":"","active":true,"console":"false","complete":"false","x":350,"y":260,"wires":[]},{"id":"9e434a37.effeb8","type":"switch","z":"14e27b21.883a85","name":"","property":"payload.srcphy","propertyType":"msg","rules":[{"t":"eq","v":"1.1.3","vt":"str"},{"t":"eq","v":"1.1.25","vt":"str"},{"t":"nnull"}],"checkall":"false","outputs":3,"x":203.10000610351562,"y":336.20001220703125,"wires":[["6d5c1c5e.f5f334"],["155edfa3.9a2b4"],["b914b986.2a9178"]]},{"id":"155edfa3.9a2b4","type":"debug","z":"14e27b21.883a85","name":"","active":true,"console":"false","complete":"false","x":370,"y":300,"wires":[]},{"id":"438785fb.38270c","type":"inject","z":"14e27b21.883a85","name":"","topic":"write","payload":"{\"srcphy\":\"1.1.3\",\"dstgad\":\"0/2/5\",\"dpt\":\"1\",\"value\":\"1\",\"type\":\"event\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":140,"wires":[["a9221435.2fe868","88718a66.6c0a28"]]},{"id":"b914b986.2a9178","type":"debug","z":"14e27b21.883a85","name":"","active":false,"console":"false","complete":"false","x":353.1000061035156,"y":365.20001220703125,"wires":[]},{"id":"88718a66.6c0a28","type":"debug","z":"14e27b21.883a85","name":"","active":true,"console":"false","complete":"payload","x":410,"y":20,"wires":[]},{"id":"34303f19.38944","type":"inject","z":"14e27b21.883a85","name":"","topic":"write","payload":"{\"dstgad\":\"0/2/3\",\"value\":0,\"dpt\":1}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":60,"wires":[["88718a66.6c0a28","a9221435.2fe868"]]},{"id":"943c998c.714ca8","type":"inject","z":"14e27b21.883a85","name":"","topic":"write","payload":"{\"dstgad\":\"0/2/3\",\"value\":1,\"dpt\":1}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":20,"wires":[["88718a66.6c0a28","a9221435.2fe868"]]},{"id":"6b1117c4.0f3428","type":"inject","z":"14e27b21.883a85","name":"","topic":"write","payload":"{\"dstgad\":\"0/2/3\",\"dpt\":\"1\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":180,"wires":[["88718a66.6c0a28","a9221435.2fe868"]]},{"id":"16bb3659.cc6dda","type":"knx-in","z":"14e27b21.883a85","name":"","controller":"40bc1d5d.22bf14","x":60,"y":291,"wires":[["9e434a37.effeb8"]]},{"id":"40bc1d5d.22bf14","type":"knx-controller","z":"","name":"BAOS777","host":"192.168.1.60","port":"3671","mode":"tunnel/unicast"}]`

**Comment by ykornilov** [comment]
Yanovik, Hi!
I tried your flow on my computer and everything worked.

after message ```[info] [knx-controller:BAOS777] already connected to knxjs server at 192.168.1.60:3671 in mode[tunnel/unicast]```
Is there a message in the console:
```[info] [knx-out:Out] sendAPDU: true```
?

What is the status of KNX-IN and KNX-OUT nodes? Connected?
Nobody connects to the gateway (BAOS) anymore?
There is only one knx-controller-node in the flow?

**Comment by yanovik** [comment]
Hi
`29 Sep 19:50:51 - [info] [knx-out:8584adae.52efd] knxout.onInput, msg[{ _msgid: '4f3f9e6b.0d3ee',  topic: 'write',  payload: { srcphy: '1.1.3', dstgad: '0/2/7', dpt: '1', value: 0 } }]
29 Sep 19:50:51 - [info] [knx-out:8584adae.52efd] groupAddrSend action[write] dstgad:0/2/7, value:0, dpt:1
29 Sep 19:50:51 - [info] [knx-controller:baos777] already connected to knxjs server at 192.168.2.208:3671 in mode[tunnel/unicast]
29 Sep 19:50:51 - [info] [knx-out:8584adae.52efd] sendAPDU: false`

- No, sendAPDU is false
- Both are connected with green dots
- Nobody is connected
- I suppose only one, system is clean, no npm packages at all. 
- Gateway is all default
any ideas?

**Comment by yanovik** [comment]
when no knx-in node in flow log is 
`29 Sep 19:59:50 - [info] [knx-out:8584adae.52efd] groupAddrSend action[write] dstgad:0/2/7, value:1, dpt:1
29 Sep 19:59:50 - [info] [knx-controller:baos777] already connected to knxjs server at 192.168.2.208:3671 in mode[tunnel/unicast]
29 Sep 19:59:50 - [info] [knx-out:8584adae.52efd] sendAPDU: true`

So KNX OUT node does not work anyway

**Comment by ykornilov** [comment]
sendAPDU shows the value that is sent to the KNX.
Please reinstall the package and send logs

**Comment by yanovik** [comment]
Don't know the reason of failure, but now works fine. Thanks!
