### ISSUE TITLE
DPT

### ISSUE THREAD

**Issue by olapola85** [estbeetoo/node-red-contrib-knx#18]
I cant read DPT values 14*

[{"id":"c9914937.ff4f2","type":"inject","z":"f49561bb.b5b9e8","name":"read status","topic":"read","payload":"{\"dstgad\":\"4/0/0\",\"dpt\":\"14\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":101,"y":245,"wires":[["b9239637.2f38a8","ab0abf9b.e1f0f"]]}]

topic: 'read',
  payload: { dstgad: '4/0/0', dpt: '14' } }]
25 Jan 23:36:44 - [info] [knx-out:b9239637.2f38a8] groupAddrSend action[read] dstgad:4/0/0, value:undefined, dpt:14
25 Jan 23:36:44 - [info] [knx-controller:cf83bf76.25995] already connected to knxjs server at 192.168.1.3:3671 in mode[tunnel/unicast]
25 Jan 23:36:44 - [info] [knx-out:b9239637.2f38a8] sendAPDU: undefined
25 Jan 23:36:49 - [info] [knx-out:b9239637.2f38a8] knxout.onInput, msg[{ _msgid: 'abaae82.abcea18',

**Comment by olapola85** [comment]
read : msg : Object
object
_msgid: "ecd8175d.abb3c8"
topic: "read"
payload: object

**Comment by aborovsky** [comment]
Hello, @olapola85! Sorry for late response.

Please, try to edit you local file `node_modules/node-red-contrib-knx/knx.js` at  [line 204:](https://github.com/estbeetoo/node-red-contrib-knx/blob/master/knx.js#L204)

Add before
`case '9': //Floating point`
the line
`case '14': //4-Octet Float Value IEEE 754`

P.S.: what type of device do you use?
P.P.S.: let me know the result for you, i'll add this improvement to the source code.

**Comment by aborovsky** [comment]
Closing it due to inactivity.
