### ISSUE TITLE
Not supported DPT 16 and DPT 10

### ISSUE THREAD

**Issue by schnti** [estbeetoo/node-red-contrib-knx#20]
Is it possible to add these two?

**Comment by aborovsky** [comment]
Did you try?

P.S.: if you use current lib and happy about it, please support me: https://bmc.xyz/aborovsky

**Comment by schnti** [comment]
<img width="320" alt="screen shot 2018-05-08 at 22 54 32" src="https://user-images.githubusercontent.com/1868482/39782572-d95ba1d4-5312-11e8-9cbc-bec9b5e71647.png">

**Comment by aborovsky** [comment]
Thx for info. I've checked the source code: now it's not supported.
Are you able to develop it and contribute into current project?

**Comment by bolfox** [comment]
DTP 14 is supported?

**Comment by waldbaer** [comment]
See my pull requests #23 and #22 supporting DPT10 and DPT16.

**Comment by aborovsky** [comment]
Both PR's on they way to be merged.
Closing this issue.
