### ISSUE TITLE
write knx out based on a knx entry?

### ISSUE THREAD

**Issue by sfdiaz1** [estbeetoo/node-red-contrib-knx#21]
Is it possible to write a knx output as a function of a knx entry?
I want to create a (fictional) KNX-device in Node-RED that can send responses on read requests.

Thanks

**Comment by aborovsky** [comment]
Hello, @sfdiaz1 !
Thank you for a question.
Sorry for soooo late reponse :)

Your question in fact sounds like: "it it possible to get and handle read datagram (type of request)".

I'm not sure, but you definitely should try to tune KNX-in node and listen for specific GAD (group address). Then try to send read datagram into the bus with device or ETS software.

Sorry, but i cant' do that test by my own.

Will the KNX-in receive "read" datagram or not depends on the implementation: https://github.com/estbeetoo/knx.js/blob/master/src/KnxReceiver.js#L131

I've copied the feature from here: https://github.com/lifeemotions/knx.net/blob/master/src/KNXLib/KnxReceiver.cs#L215

Both are the same.

If knx.js driver library will receive the datagram but it's type is unknown, then you'll get the string in Node-RED's stdout (console output, not a debug tab): 
```
Unknown type[X] received in datagram[Y]
```
If you'll get this, post it here and i'll be able to implement the feature.
