### ISSUE TITLE
node type unknown

### ISSUE THREAD

**Issue by pentadom** [estbeetoo/node-red-contrib-knx#24]
Hello,

I'm running node-red (v0.15.3) in a Multitech Conduit Hardware, and it's returning the next error:

![image](https://user-images.githubusercontent.com/44440500/49155520-70fb8b00-f31b-11e8-946d-a11c46e943e3.png)

I did again a npm install

Then I restart de node-red and then the log command:

![image](https://user-images.githubusercontent.com/44440500/49155568-88d30f00-f31b-11e8-8ae1-0f84cfd86b46.png)

Here's the post in node-red forum for more information: https://discourse.nodered.org/t/remove-node-from-node-red/5217

Which could be the error?

**Comment by aborovsky** [comment]
You use old Node-RED verion - v0.15.3
Try to update it to v4 at least.

Linux 3.12.70 arm LE - do you run it under Raspberry Pi?
Manual for Raspberry Pi: https://www.w3schools.com/nodejs/nodejs_raspberrypi.asp
Check "Install Node.js on Raspberry Pi" section.

**Comment by pentadom** [comment]
> You use old Node-RED verion - v0.15.3
> Try to update it to v4 at least.
> 
> Linux 3.12.70 arm LE - do you run it under Raspberry Pi?
> Manual for Raspberry Pi: https://www.w3schools.com/nodejs/nodejs_raspberrypi.asp
> Check "Install Node.js on Raspberry Pi" section.

Hi,

Unfortunately, due to the Conduit hardware, the max Node-Red version and Node.js version that the Conduit can take is:

Node-red: v0.15.3

Node.js: v0.10.48

The node requirement is:

Node.js v4.5.0 and above
Node-RED v0.12.0 and above

So de problem is in the Node.js that I can't upgrade on the Conduit machine. So I can't use KNX for this function. thanks

**Comment by aborovsky** [comment]
Technically, one able to fix the code to support old Node.js.
You may find a JS freelancer to help you with it.

For example: find the file "/var/config/app/install/development/node_modules/node-red-contrib-knx/node_modules/knxjs/src/KnxHelper.js" and replace on the line 279:
`var exponent = (apu[2] & 0x01111000) >>> 3;`
with:
`var exponent = (apu[2] & parseInt('01111000', 2)) >>> 3;`

**Comment by pentadom** [comment]
> Technically, one able to fix the code to support old Node.js.
> You may find a JS freelancer to help you with it.
> 
> For example: find the file "/var/config/app/install/development/node_modules/node-red-contrib-knx/node_modules/knxjs/src/KnxHelper.js" and replace on the line 279:
> `var exponent = (apu[2] & 0x01111000) >>> 3;`
> with:
> `var exponent = (apu[2] & parseInt('01111000', 2)) >>> 3;`

I will try another option without using the knx node. Thanks!
