### ISSUE TITLE
Error: error calling groupAddrSend: TypeError [ERR_INVALID_ARG_TYPE] when update to nodejs 11.6.0

### ISSUE THREAD

**Issue by remspoor** [estbeetoo/node-red-contrib-knx#25]
Thanks for this great node!
But after using it for about 2 years now, i can't control the lights in my house anymore from Node-Red.
### Issue:
After updating nodejs 10.x.x to nodejs 11.6.0 (11.7.0 now) the KNX-out gives errors when sending a message. KNX-in works though.
### Setup:
I'm running Node-Red on a raspberry pi2 and an orangepipc. Both have an up to date Arch linux installation.
![image](https://user-images.githubusercontent.com/1766096/51434485-9e9cea80-1c61-11e9-8b6d-678f1cb55dd7.png)
Topic: `knx:write`
Payload: `{ "srcphy": "15.15.249", "dstgad": "1/1/51", "dpt": "1", "value": "1", "type": "event" }`
### Errors:
```Jan 20 02:57:56 orangepipc Node-RED[282]: 20 Jan 02:57:56 - [error] [knx-out:KNX-out (tunnel)] error calling groupAddrSend: TypeError [ERR_INVALID_ARG_TYPE]: The "byteLength" argument must be of type number. Received type undefined```
`Jan 20 02:57:56 orangepipc Node-RED[282]: 20 Jan 02:57:56 - [error] [knx-out:KNX-out (tunnel)] groupAddrSend error: TypeError [ERR_INVALID_ARG_TYPE]: The "byteLength" argument must be of type number. Received type undefined`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at validateNumber (internal/validators.js:130:11)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at boundsError (internal/buffer.js:51:5)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at Buffer.writeIntLE (internal/buffer.js:691:3)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxConnectionTunneling.KnxConnection.Action (/home/nodered/node_modules/knx.js/src/KnxConnection.js:87:21)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at /home/nodered/node_modules/node-red-contrib-knx/knx.js:260:37`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxControllerNode.initializeKnxConnection (/home/nodered/node_modules/node-red-contrib-knx/knx.js:37:21)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxOut.groupAddrSend (/home/nodered/node_modules/node-red-contrib-knx/knx.js:242:27)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxOut.<anonymous> (/home/nodered/node_modules/node-red-contrib-knx/knx.js:107:18)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxOut.emit (events.js:188:13)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at KnxOut.Node.receive (/home/nodered/node_modules/node-red/red/runtime/nodes/Node.js:215:14)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at InjectNode.Node.send (/home/nodered/node_modules/node-red/red/runtime/nodes/Node.js:137:22)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at InjectNode.<anonymous> (/home/nodered/node_modules/node-red/nodes/core/core/20-inject.js:78:26)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at InjectNode.emit (events.js:188:13)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at InjectNode.Node.receive (/home/nodered/node_modules/node-red/red/runtime/nodes/Node.js:215:14)`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at /home/nodered/node_modules/node-red/nodes/core/core/20-inject.js:117:22`
`Jan 20 02:57:56 orangepipc Node-RED[282]:     at Layer.handle [as handle_request] (/home/nodered/node_modules/express/lib/router/layer.js:95:5)`

I hope this can be fixed, because i really don't know how to fix this myself.
Thanks very much

#### Edit:
Huumm, looks like i managed to debug this a bit myself.
It seems like the issue is in file `KnxConnection.js` from package `knx.js` [line 87](https://github.com/estbeetoo/knx.js/blob/master/src/KnxConnection.js#L87).
I changed `buf.writeIntLE(data ? 1 : 0);` to `buf.writeInt8(data ? 1 : 0);` and things seem to work again.
See this [change to nodejs](https://github.com/nodejs/node/commit/60b5b38b4854005f11f008b510a57eab24025599#diff-b3fd3826a3678e1d85310d90c3d6f917L677)
Hopefully this is the right thing to change.

**Comment by aborovsky** [comment]
Fixed with: https://github.com/estbeetoo/knx.js/commit/9659059837392e776a3cd6bafda3f56ab9a363b4
