### ISSUE TITLE
Wrong value conversion on dpt 5.001

### ISSUE THREAD

**Issue by jo3ran** [estbeetoo/node-red-contrib-knx#28]
Hi guys

I've used to run knx.js with the version, that came with the node-red Ui palette installer. At that time, sent values with dpt 5.001 worked well. Some days ago i've pulled the latest one from the git repo and now those values stopped working.
Looking at the code, one would assume, that all dpt cases before 10 (time) run into this case and get interpreted as time input. Is this intended?

```
case '5':    //8-bit unsigned value               1 Byte                  EIS 6         DPT 5    0...255
case '5.001':    //8-bit unsigned value               1 Byte                  DPT 5.001    DPT 5.001    0...100
case '6':    //8-bit signed value                 1 Byte                  EIS 14        DPT 6    -128...127
case '7':    //16-bit unsigned value              2 Byte                  EIS 10        DPT 7    0...65535
case '8':    //16-bit signed value                2 Byte                  DPT 8         DPT 8    -32768...32767
case '10':   //Time                               3 Byte                  EIS 3         DPT 10    Day [0..7] Hour [0..23] Minutes [0..59] Seconds [0..59]
  var day = 0;
```

May I also kindly request to reopen issue 6 - I've added a comment there.
Thank you very much for your effort to this project!

Best
jo3ran

**Comment by fiLLLip** [comment]
I am having issues with dpt 7 as well. Just looked at the code and now I see what is causing it. If wanted, I could try to create a pull request. :)

**Comment by aborovsky** [comment]
Fix published: https://www.npmjs.com/package/node-red-contrib-knx/v/0.10.0
