### ISSUE TITLE
wonderful module, help with example to get GA to chart

### ISSUE THREAD

**Issue by ozett** [estbeetoo/node-red-contrib-knx#3]
hi,
wonderful module. i am playing with it.
not much in google about creating functions, i am not so good in programming.

:smiley:  **may you help me out with describing an example function to get the value
of a specific GA(group-adress) in a timed interval?**  :smiley: 

the code of knx-parse function is a sample from another flow. 
i wanted to modify it, but i am a little bit alone in space ....

anyhelp very appreciated, thhaaannks a lot...

![zwischenablage01-2](https://cloud.githubusercontent.com/assets/5937811/14912130/75afb562-0dfa-11e6-9322-9803760e9972.png)

**Comment by aborovsky** [comment]
Hi, ozett,
Thank you for response! Your attention to the module is pleasure for us :)

Please, paste your JS code (of function node-red's node, i suppose) here.
And try to explain - how exactly you want to modify it.
I'll try to give you an advice.

**Comment by ozett** [comment]
hi, thank for your fast reply, 
your module is a pleasure for me.. :smile: 

what i want to do: 
i want to build the same diagrams i have from my ESPeasy modules via MQTT comin  in to node-red
with my knx-devices. 
![zwischenablage1-knx](https://cloud.githubusercontent.com/assets/5937811/14912396/43510b96-0dfc-11e6-8a1b-09b7298d48c2.png)

**Comment by ozett** [comment]
but i am not able to build a working flow.. :worried:

i only need the temperatur-value from my GA 3/2/11 to feed into the chart-module of the node-red-gui.
i dont know how to get this in a timed interval (may 2 min..) and only the value from the ga of the knx-node. i am unsure, if i need an inject node, and how to build this exactly.
may you can help me out..?  :flushed:

![zwischenablage06](https://cloud.githubusercontent.com/assets/5937811/14912513/1d5ae80c-0dfd-11e6-9d7d-bd6ea5f38f72.png)

what i have: 
the knx-connection is working, i have debug-messages and can feed the msg.payload to a text-node.

**Comment by ozett** [comment]
to basic question for experienced user?
sorry,.. :cold_sweat:

**Comment by ozett** [comment]
i tried to quirk some code like this in a function, but that did not work out..

> var  map = {
>     '3/2/11' : {"nodeid": 5, "value": msg.payload.value},
>     '2/2/51' : {"nodeid": 5, "cmdclass": 38, "value": msg.payload.value},
>     '2/2/81':  {"nodeid": 8, "instance":1, "value": msg.payload.value},
>     '2/2/82':  {"nodeid": 8, "instance":2, "value": msg.payload.value},
>     '2/2/90' : {"nodeid": 9, "value": msg.payload.value}
> }
> switch (msg.topic) {
> // or forward them to KNX
> //case "knx: read":
> case "read":
>     if (msg.payload.dstgad in map) {
>         var response = {"topic": "setValue", "payload": map[msg.payload.dstgad] };
>         console.log('== knx to zwave: %j', response);
>         return response;
>     }
> }
> return;

![zwischenablage01-2](https://cloud.githubusercontent.com/assets/5937811/14923702/f18f225a-0e3e-11e6-899c-9216cecf85b4.png)

**Comment by aborovsky** [comment]
I'll take a look in 12hours. Need to spent time with my family, sorry :)
Пт, 29 апр. 2016 г. в 20:17, ozett notifications@github.com:

**Comment by ozett** [comment]
thanks for reply... do so, :family: more important than bits&bytes (at least)..

**Comment by aborovsky** [comment]
Proper flow for your case will be:
1. inject node [with timer configured] -- read request --> knx out [write] node
2. knx in [read] node ---->  chart node of node-red-contrib-ui

Right now you trying to send msg with topic 'read' in knx-out node.
But underlying library knx.js doesn't support yet such kind of datagrams.

If you'll analyze stdout [or stderr] of node.js process you'll see the line:

`Unsupported action[read] inside of groupAddrSend`

Conclusion: read command should be implemented.

I'll close this ticket.

Please, contact me directly by email: aborovsky@beetoo.me. I'll try to help you.

**Comment by ozett** [comment]
thanks for suggestion how to build the flow-connections.
i did it like you advised, and now see the "knx out [write] node" as inactive,
and i attach a picture, how i set up the inject node.
i am still doing something wrong, but .... thankx...

after that: how can i select the "knx-in-node" for other GADs for charting? 
i cannot see how to do this...
thaaanks a lot, :smiley: 

![zwischenablage01](https://cloud.githubusercontent.com/assets/5937811/14941615/e28e4fba-0fa1-11e6-9f4f-551169f5f06b.png)
