### ISSUE TITLE
No matching version found at install

### ISSUE THREAD

**Issue by powerzumsel** [estbeetoo/node-red-contrib-knx#31]
I wanted to install this node on fresh node-red but dependency was not found

> 
> 28 verbose node v12.18.4
> 29 verbose npm  v6.14.6
> 30 error code ETARGET
> 31 error notarget No matching version found for knx.js@^0.7.5.
> 32 error notarget In most cases you or one of your dependencies are requesting
> 32 error notarget a package version that doesn't exist.
> 32 error notarget
> 32 error notarget It was specified as a dependency of 'node-red-contrib-knx'
>

**Comment by MariusLang** [comment]
Unfortunately I have the same problem...
Does anybody has an idea how to solve that problem?

**Comment by hi1000** [comment]
knx.js the latest public version is 0.7.4 not 0.7.5

**Comment by nioc** [comment]
You can install 0.9.0 which is not using knx.js 0.7.5 (which is not published):
`npm install node-red-contrib-knx@0.9.0`

**Comment by nioc** [comment]
Hi @powerzumsel @hi1000 @MariusLang knx.js 0.7.5 has been released on npm, so you can update your node-red-contrib-knx to latest (0.10.0) version.
May be this issue should be closed?

**Comment by MariusLang** [comment]
I have installed the node in my NodeRed development environment. node-red-contrib-knx@0.10.0 works great for me.
So the issue can be closed.
