### ISSUE TITLE
Feature-Request: Documentation/wiki help

### ISSUE THREAD

**Issue by ozett** [estbeetoo/node-red-contrib-knx#4]
may you put the DPT list on your wiki?
its of help with knx...

i googled them for me:
https://github.com/andreek/node-eibd
http://www.loxone.com/dede/service/dokumentation/loxone-config/eib-knx/datentypen.html

**Comment by aborovsky** [comment]
According Wiki page was created: https://github.com/estbeetoo/node-red-contrib-knx/wiki/KNX-DPT-Types
