### ISSUE TITLE
Error when calling knx-out node

### ISSUE THREAD

**Issue by flashpoint90** [estbeetoo/node-red-contrib-knx#9]
Everytime i try to send a msg to the output node, node-red crashes with this error message:

> 19 Jun 21:08:57 - [red] Uncaught Exception:
> 19 Jun 21:08:57 - TypeError: callback is not a function
> at SendWrap.cb as callback (C:\Users\KNX\AppData\Roaming\npm\node_modules\node-red-contrib-knx\node_modules\knx.js\src\KnxSenderTunneling.js:40:21)
> at SendWrap.afterSend as oncomplete (dgram.js:347:8)

I also tried a setup with just a test injection and it still crashes with the error above, as soon as i try to inject the msg.
![node-red-knx_01](https://cloud.githubusercontent.com/assets/11891758/16179354/8b5fe27e-3663-11e6-94cc-b9e1805f9b75.jpg)

Everything else (KNX connection itself & input node) is working fine.

Used version:

> 19 Jun 21:14:53 - [info] Node-RED version: v0.13.4
> 19 Jun 21:14:53 - [info] Node.js  version: v4.4.5
> 19 Jun 21:14:53 - [info] Windows_NT 6.1.7600 x64 LE

Any help would be greatly appreciated!

**Comment by aborovsky** [comment]
We've published new version [v0.7.1] to npmjs.com.
Try to update it with cmd:
`$ npm install node-red-contrib-knx@lastest`
Current problem closed with commit [3381e87](https://github.com/estbeetoo/node-red-contrib-knx/pull/5/commits/3381e87d48aab876cfff93ac5c48b9d638796014)

**Comment by flashpoint90** [comment]
Thanks a lot abarovsky this worked for my problem!
